# Site settings
title: 老翅寒暑
SEOTitle: 老翅寒暑 | BigTall Blog
header-img: img/home-bg-desk.jpg
#email: jiangjianbo@gmail.com
description: "一个老鸟的自白"
keyword: "BigTall, BigTall Blog, 老翅寒暑, archetype, software design, OOA, OOD"
url: "http://jiangjianbo.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jiangjianbo/jiangjianbo.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "To B, or not to B, that is the question."
sidebar-avatar: /img/about-bigtall-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
#zhihu_username:     
github_username:    jiangjianbo
#facebook_username:  
#jianshu_username:   
#twitter_username:   



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "package-lock.json",
    "README.md",
    "README.zh.md",
    "Rakefile"
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# plugins: [jekyll-paginate]
plugins:
  - "jekyll-paginate"
  - "kramdown-plantuml"
#  - "jekyll-spaceship"

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plantuml:
  plantuml_jar: /Users/jiangjianbo/win-share/program/plantuml/plantuml-nodot.1.2022.13.jar     # path to plantuml jar
  tmp_folder: _plantuml               # tmp folder to put generated image files
  dot_exe: /usr/local/bin/dot         # [optional] path to Graphviz dot execution
  background_color: white             # [optional] UML image background color

  type: utxt                         # type (passed as -t option, ex: -tutxt)
  extension: txt                     # output extension override
  plantuml_args: -nometadata         # extra args to be passed to plantuml
  java_args: -Xmx1G                  # extra args to be passed to java


jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/

# Disqus settings
# disqus_username: xxx

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: d7cd8d69d6e30316f49a       #生成的clientID
  clientSecret: b06644150e9889cc8ec266646f9f0594f8a8192c    #生成的clientSecret
  repo: jiangjianbo.github.io    #仓库名称
  owner: jiangjianbo    #github用户名
  admin: jiangjianbo
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: 74342d6ddffd6472427b688c4e05dd3f

# Google Analytics
#ga_track_id: 'UA-137375520-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
        title: "博客园·老翅寒暑",
        href: "http://bigtall.cnblogs.com"
    },{
        title: "微信个人号·老翅寒暑",
        image: true,
        href: "/img/qrcode-bigtall.png"
    }
]
